from typing import Dict

# List of all gemium plants (including sun producers)
gemium_plants = [
    "Power Lily",
    "Jalapeno",
    "Imitater",
    "Starfruit",
    "Hypno-shroom",
    "Pea-nut",
    "Chomper",
    "Homing Thistle",
    "Hurrikale",
    "Fire Peashooter",
    "Lava Guava",
    "Toadstool",
    "Cactus",
    "Electric Blueberry",
    "Jack O' Lantern",
    "Grapeshot",
    "Cold Snapdragon",
    "Shrinking Violet",
    "Escape Root",
    "Explode-O-nut",
    "Apple Mortar",
    "Missile Toe",
    "Caulipower",
    "Electric Peashooter",
    "Bamboozle",
    "Snowdrop",
    "Zoybean Pod",
    "Pyre Vine",
    "Cran Jelly",
    "Dragon Bruit",
    "Snap Pea"
]

# List of all epic plants (including sun producers)
epic_plants = [
    "Gloom Vine",
    "Shadow Peashooter",
    "Murkadamia Nut",
    "Noctarine",
    "Shooting Starfruit",
    "Strawburst",
    "Aloe",
    "Holly Knight",
    "Iceweed",
    "Squash",
    "Dandelion",
    "Pea Vine",
    "Buttercup",
    "Sap-fling",
    "Electric Currant",
    "Solar Tomato",
    "Plantern",
    "Vamporcini",
    "Ice-shroom",
    "Doom-shroom",
    "Ghost Pepper",
    "Parsnip",
    "Ice Bloom",
    "Sweet Potato",
    "Hot Date",
    "Gatling Pea",
    "Mega Gatling Pea",
    "Torchwood",
    "Atomic Bombergranate",
    "Blooming Heart",
    "Gold Bloom",
    "Gloom-Shroom",
    "Umbrella Leaf",
    "Pumpkin",
    "Shine Vine",
    "Gumnut",
    "Meteor Flower",
    "Seashooter",
    "Floawer Pot"
]

# List of all world plants (including sun producers)
world_plants = [
    "Cabbage-pult",
    "Bloomerang",
    "Iceburg Lettuce",
    "Grave Buster",
    "Bonk Choy",
    "Repeater",
    "Twin Sunflower",
    "Kernel-pult",
    "Snapdragon",
    "Spikeweed",
    "Coconut Cannon",
    "Spring Bean",
    "Threepeater",
    "Spikerock",
    "Cherry Bomb",
    "Split Pea",
    "Chili Bean",
    "Lightning Reed",
    "Tall-nut",
    "Pea Pod",
    "Melon-pult",
    "Winter Melon",
    "Fire Gourd",
    "Snow Pea",
    "Resitant Radish",
    "Heavenly Peach",
    "Bamboo Shoot",
    "Cantaloupe-pult",
    "Solar Sage",
    "Lychee",
    "Laser Bean",
    "Blover",
    "Citron",
    "E.M. Peach",
    "Infi-nut",
    "Magnifying Grass",
    "Tile Turnip",
    "Sun-shroom",
    "Puff-shroom",
    "Fume-shroom",
    "Sun Bean",
    "Magnet-shroom",
    "Scaredy Shroom",
    "Lily Pad",
    "Tangle Kelp",
    "Bowling Bulb",
    "Guacodile",
    "Banana Launcher",
    "Hot Potato",
    "Pepper-pult",
    "Chard Guard",
    "Stunion",
    "Rotobaga",
    "Red Stinger",
    "A.K.E.E.",
    "Endurian",
    "Stallia",
    "Gold Leaf",
    "Skyshooter",
    "Moon Bean",
    "Phat Beet",
    "Celery Stalker",
    "Thyme Warp",
    "Garlic",
    "Spore-shroom",
    "Intensive Carrot",
    "Primal Peashooter",
    "Primal Wall-nut",
    "Perfume-shroom",
    "Primal Sunflower",
    "Primal Potato Mine",
    "Peashooter",
    "Sunflower",
    "Wall-nut",
    "Potato Mine",
    "Marigold",
    "Moonflower",
    "Nightshade",
    "Shadow-shroom",
    "Dusk Lobber",
    "Grimrose",
]

# List of all mints (including sun producers)
mints = [
    "Fila-mint",
    "Reinforce-mint",
    "Bombard-mint",
    "Arma-mint",
    "Contain-mint",
    "Enchant-mint",
    "Spear-mint",
    "Pepper-mint",
    "Winter-mint",
    "Conceal-mint",
    "Enforce-mint",
    "Enlighten-mint",
    "Ail-mint",
    "Appease-mint"
]

# List of unobtainable plants
unobtainable_plants = [
    "Skyshooter",
    "Moon Bean",
    "Dragon Bruit",    
    "Floawer Pot",
    "Shadow Peashooter",
    "Murkadamia Nut",
    "Conceal-mint",
    "Appease-mint",
    "Enlighten-mint",
    "Noctarine",
    "Gloom Vine"
]

# List of sun producers
sun_producers = [
    "Sunflower",
    "Sun-shroom",
    "Twin Sunflower",
    "Moonflower",
    "Primal Sunflower",
    "Shinevine",
]

# List of sun plants
sun_plants = [
    "Sunflower",
    "Sun-shroom",
    "Twin Sunflower",
    "Moonflower",
    "Primal Sunflower",
    "Shinevine",
    "Sun Bean",
    "Solar Sage",
    "Solar Tomato",
    "Moon Bean",
    "Plantern",
    "Toadstool",
    "Gold Bloom",
    "Gold Leaf",
    "Enlighten-mint"
]

# List of aquatic plants
aquatic_plants = [
    "Lily Pad",
    "Tangle Kelp"
]

sun_cost: Dict[str, int] = {
    "Cabbage-pult" : 100,
    "Bloomerang" : 175,
    "Iceburg Lettuce" : 0,
    "Grave Buster" : 0,
    "Bonk Choy" : 150,
    "Repeater" : 200,
    "Twin Sunflower" : 125,
    "Kernel-pult" : 100,
    "Snapdragon" : 150,
    "Spikeweed" : 100,
    "Coconut Cannon" : 400,
    "Spring Bean" : 50,
    "Threepeater" : 300,
    "Spikerock" : 250,
    "Cherry Bomb" : 150,
    "Split Pea" : 125,
    "Chili Bean" : 50,
    "Lightning Reed" : 125,
    "Tall-nut" : 125,
    "Pea Pod" : 125,
    "Melon-pult" : 325,
    "Winter Melon" : 500,
    "Fire Gourd" : 200,
    "Snow Pea" : 150,
    "Resitant Radish" : 50,
    "Heavenly Peach" : 125,
    "Bamboo Shoot" : 175,
    "Cantaloupe-pult" : 500,
    "Solar Sage" : 75,
    "Lychee" : 150,
    "Laser Bean" : 200,
    "Blover" : 50,
    "Citron" : 350,
    "E.M. Peach" : 25,
    "Infi-nut" : 75,
    "Magnifying Grass" : 50,
    "Tile Turnip" : 250,
    "Sun-shroom" : 25,
    "Puff-shroom" : 0,
    "Fume-shroom" : 125,
    "Sun Bean" : 50,
    "Magnet-shroom" : 100,
    "Scaredy Shroom" : 25,
    "Lily Pad" : 25,
    "Tangle Kelp" : 25,
    "Bowling Bulb" : 200,
    "Guacodile" : 125,
    "Banana Launcher" : 500,
    "Hot Potato" : 0,
    "Pepper-pult" : 200,
    "Chard Guard" : 75,
    "Stunion" : 25,
    "Rotobaga" : 150,
    "Red Stinger" : 150,
    "A.K.E.E." : 175,
    "Endurian" : 100,
    "Stallia" : 0,
    "Gold Leaf" : 50,
    "Skyshooter" : 150,
    "Moon Bean" : 25,
    "Phat Beet" : 150,
    "Celery Stalker" : 50,
    "Thyme Warp" : 75,
    "Garlic" : 50,
    "Spore-shroom" : 150,
    "Intensive Carrot" : 100,
    "Primal Peashooter" : 175,
    "Primal Wall-nut" : 75,
    "Perfume-shroom" : 150,
    "Primal Sunflower" : 75,
    "Primal Potato Mine" : 50,
    "Peashooter" : 100,
    "Sunflower" : 50,
    "Wall-nut" : 50,
    "Potato Mine" : 25,
    "Marigold" : 50,
    "Moonflower" : 50,
    "Nightshade" : 75,
    "Shadow-shroom" : 50,
    "Dusk Lobber" : 150,
    "Grimrose" : 75,
    "Power Lily" : 175,
    "Jalapeno" : 125,
    "Imitater" : -666,
    "Starfruit" : 150,
    "Hypno-shroom" : 125,
    "Pea-nut" : 150,
    "Chomper" : 150,
    "Homing Thistle" : 250,
    "Hurrikale" : 100,
    "Fire Peashooter" : 175,
    "Lava Guava" : 75,
    "Toadstool" : 200,
    "Strawburst" : 400,
    "Cactus" : 175,
    "Electric Blueberry" : 150,
    "Jack O' Lantern" : 225,
    "Grapeshot" : 150,
    "Cold Snapdragon" : 225,
    "Shrinking Violet" : 50,
    "Escape Root" : 50,
    "Explode-O-nut" : 50,
    "Apple Mortar" : 250,
    "Missile Toe" : 500,
    "Caulipower" : 250,
    "Electric Peashooter" : 200,
    "Aloe" : 75,
    "Holly Knight" : 150,
    "Snowdrop" : 200,
    "Iceweed" : 150,
    "Bamboozle" : 225,
    "Squash" : 50,
    "Dandelion" : 275,
    "Pea Vine" : 125,
    "Buttercup" : 25,
    "Sap-fling" : 75,
    "Electric Currant" : 150,
    "Shooting Starfruit" : 500,
    "Solar Tomato" : 100,
    "Plantern" : 75,
    "Vamporcini" : 100,
    "Ice-shroom" : 300,
    "Doom-shroom" : 225,
    "Ghost Pepper" : 75,
    "Parsnip" : 150,
    "Ice Bloom" : 200,
    "Sweet Potato" : 150,
    "Hot Date" : 175,
    "Gatling Pea" : 450,
    "Mega Gatling Pea" : 450,
    "Torchwood" : 175,
    "Atomic Bombergranate" : 225,
    "Blooming Heart" : 150,
    "Gold Bloom" : 0,
    "Gloom-Shroom" : 250,
    "Umbrella Leaf" : 100,
    "Zoybean Pod" : 200,
    "Pyre Vine" : 125,
    "Pumpkin" : 150,
    "Shine Vine" : 75,
    "Gumnut" : 125,
    "Gloom Vine" : 125,
    "Meteor Flower" : 250,
    "Seashooter" : 275,
    "Cran Jelly" : 75,
    "Dragon Bruit" : 200,    
    "Floawer Pot" : 100,
    "Shadow Peashooter" : 125,
    "Murkadamia Nut" : 100,
    "Noctarine" : 150,
    "Snap Pea" : 200,
    "Fila-mint" : 0,
    "Reinforce-mint" : 0,
    "Bombard-mint" : 0,
    "Arma-mint" : 0,
    "Contain-mint" : 0,
    "Enchant-mint" : 0,
    "Spear-mint" : 0,
    "Pepper-mint" : 0,
    "Winter-mint" : 0,
    "Conceal-mint" : 0,
    "Enforce-mint" : 0,
    "Enlighten-mint" : 0,
    "Ail-mint" : 0,
    "Appease-mint" : 0
}