import random

# List of sun producers
sun_producers = [
    "Sunflower",
    "Sun-shroom",
    "Twin Sunflower",
    "Moonflower",
    "Primal Sunflower",
    "Shinevine",
]

# List of sun plants
sun_plants = [
    "Sunflower",
    "Sun-shroom",
    "Twin Sunflower",
    "Moonflower",
    "Primal Sunflower",
    "Shinevine",
    "Sun Bean",
    "Solar Sage",
    "Solar Tomato",
    "Moon Bean",
    "Plantern",
    "Toadstool",
    "Gold Bloom",
    "Enlighten-mint"
]

# List of all premium plants (including sun producers)
premium_plants = [
    "Power Lily",
    "Jalapeno",
    "Imitater",
    "Starfruit",
    "Hypno-shroom",
    "Pea-nut",
    "Chomper",
    "Homing Thistle",
    "Hurrikale",
    "Fire Peashooter",
    "Lava Guava",
    "Toadstool",
    "Strawburst",
    "Cactus",
    "Electric Blueberry",
    "Pyrevine",
    "Jack O' Lantern",
    "Grapeshot",
    "Cold Snapdragon",
    "Shrinking Violet",
    "Escape Root",
    "Wasabi Whip",
    "Explode-O-nut",
    "Kiwibeast",
    "Apple Mortar",
    "Bombegranate",
    "Missile Toe",
    "Caulipower",
    "Electric Peashooter",
    "Aloe",
    "Holly Barrier",
    "Snowdrop",
    "Iceweed",
    "Bamboozle",
    "Squash",
    "Dandelion",
    "Pea Vine",
    "Buttercup",
    "Sap-fling",
    "Electric Currant",
    "Shooting Starfruit",
    "Solar Tomato",
    "Plantern",
    "Vamporcini",
    "Ice Shroom",
    "Doom Shroom",
    "Ghost Pepper",
    "Parsnip",
    "Icebloom",
    "Sweet Potato",
    "Hot Date",
    "Gatling Pea",
    "Mega Gatling Pea",
    "Torchwood",
    "Atomic Bombergranate",
    "Blooming Heart",
    "Gold Bloom",
    "Gloom-Shroom",
    "Umbrella Leaf",
    "Zoybean Pod",
    "Pyre Vine",
    "Pumpkin",
    "Shine Vine",
    "Gumnut",
    "Gloom Vine",
    "Meteor Flower",
    "Seashooter",
    "Cran Jelly",
]

# List of all world plants (including sun producers)
world_plants = [
    "Cabbage-pult",
    "Bloomerang",
    "Iceburg Lettuce",
    "Grave Buster",
    "Bonk Choy",
    "Repeater",
    "Twin Sunflower",
    "Kernel-pult",
    "Snapdragon",
    "Spikeweed",
    "Coconut Cannon",
    "Spring Bean",
    "Threepeater",
    "Spikerock",
    "Cherry Bomb",
    "Split Pea",
    "Chili Bean",
    "Lightning Reed",
    "Tall-nut",
    "Pea Pod",
    "Melon-pult",
    "Winter Melon",
    "Fire Gourd",
    "Snow Pea",
    "Resitant Radish",
    "Heavenly Peach",
    "Bamboo Shoot",
    "Cantaloupe-pult",
    "Solar Sage",
    "Lychee",
    "Laser Bean",
    "Blover",
    "Citron",
    "E.M. Peach",
    "Infi-nut",
    "Magnifying Grass",
    "Tile Turnip",
    "Sun-shroom",
    "Puff-shroom",
    "Fume-shroom",
    "Sun Bean",
    "Magnet-shroom",
    "Scaredy Shroom",
    "Lily Pad",
    "Tangle Kelp",
    "Bowling Bulb",
    "Guacodile",
    "Banana Launcher",
    "Hot Potato",
    "Pepper-pult",
    "Chard Guard",
    "Stunion",
    "Rotobaga",
    "Red Stinger",
    "A.K.E.E.",
    "Endurian",
    "Stallia",
    "Gold Leaf",
    "Phat Beet",
    "Celery Stalker",
    "Thyme Warp",
    "Garlic",
    "Spore-shroom",
    "Intensive Carrot",
    "Primal Peashooter",
    "Primal Wall-nut",
    "Perfume-shroom",
    "Primal Sunflower",
    "Primal Potato Mine",
    "Peashooter",
    "Sunflower",
    "Wall-nut",
    "Potato Mine",
    "Marigold",
    "Moonflower",
    "Nightshade",
    "Shadow-shroom",
    "Dusk Lobber",
    "Grimrose",
]

# List of all mints (including sun producers)
mints = [
    "Fila-mint",
    "Reinforce-mint",
    "Bombard-mint",
    "Arma-mint",
    "Contain-mint",
    "Enchant-mint",
    "Spear-mint",
    "Pepper-mint",
    "Winter-mint",
    "Conceal-mint",
    "Enforce-mint",
    "Enlighten-mint",
    "Ail-mint",
    "Appease-mint"
]

unobtainable_plants = [
    "Skyshooter",
    "Moon Bean",
    "Dragon Bruit",    
    "FloawerPot",
    "Shadow Peashooter",
    "Murkadamia Nut",
    "Conceal-mint",
    "Appease-mint",
    "Enlighten-mint",
]

